# Generated by Django 3.2.25 on 2025-10-07 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='authentication.team', verbose_name='Zugewiesenes Team'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='co_assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets_co', to=settings.AUTH_USER_MODEL),
        ),
    ]
